name: Docker CI Pipeline

on:
  push:
    branches:
      - main  # Cambia por la rama que desees
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out el código
      - name: Check out repository
        uses: actions/checkout@v2

      # Establecer el Docker Hub y otras variables
      - name: Set up Docker registry
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE_NAME: 'my-app'
          TAG: ${{ github.sha }}
        run: echo "Registry: $DOCKER_REGISTRY, Image: $IMAGE_NAME, Tag: $TAG"

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$TAG .

      # Iniciar sesión en Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Ejecutar pruebas unitarias
      - name: Run Unit Tests
        run: |
          npm install
          npm test

      # Análisis estático del código con ESLint
      - name: Run Static Code Analysis (ESLint)
        run: |
          npm install
          npm run lint

      # Generar cobertura de código con Jest
      - name: Run Test Coverage with Jest
        run: |
          npm install
          npm run test-coverage

      # Subir imagen Docker al registro
      - name: Push Docker image
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TAG
